chandelier_web/apps/home_page/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.indexHome.as_view(), name='indexHome'),
    
    path('ubicaciones/<str:reference>/<id>/', views.locationHome.as_view(), name='locationHome'),
    path('ubicacion/<id>/informacion/', views.locationInfoHome.as_view(), name='locationInfoHome'),
    
    path('cotizar/<id>', views.quoteHome.as_view(), name='quoteHome'),
    path('cotizacion_rapida/', views.fastQuoteHome.as_view(), name='fastQuoteHome'),
    
    path('acerca_de/', views.aboutUsHome.as_view(), name='aboutHome'),
    path('contactanos/', views.contactHome.as_view(), name='contactHome'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # # User management
    path("users/", include("chandelier_web.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path('', include('chandelier_web.apps.home_page.urls')),
    path('', include('chandelier_web.apps.admin_page.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

chandelier_web/apps/admin_page_locations/models.py
from django.db import models
from chandelier_web.apps.admin_page_states.models import State
from chandelier_web.apps.admin_page_themes.models import Theme

# Create your models here.
class Location(models.Model):
    name = models.CharField(max_length=100)
    owner = models.CharField(max_length=100)
    location = models.CharField(max_length=200)
    location_length = models.CharField(max_length=200, blank=True, null=True)
    location_width = models.CharField(max_length=200, blank=True, null=True)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE)
    capacity = models.IntegerField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    description = models.TextField(blank=True)
    web_site = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    parking = models.BooleanField(default=False)

    def __str__(self):
        return self.name
      
class Image(models.Model):
    location = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='location_images', blank=True, null=True)

    def __str__(self):
        return str(self.image)

class OpeningHour(models.Model):
    WEEKDAYS = (
        (1, 'Lunes'),
        (2, 'Martes'),
        (3, 'Miércoles'),
        (4, 'Jueves'),
        (5, 'Viernes'),
        (6, 'Sábado'),
        (7, 'Domingo'),
    )
    location = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='opening_hours')
    day_of_week = models.IntegerField(choices=WEEKDAYS, blank=True, null=True)
    opening_time = models.TimeField(blank=True, null=True)
    closing_time = models.TimeField(blank=True, null=True)

    def __str__(self):
        return self.day_of_week

# class Location(models.Model):
#     name = models.CharField(max_length=100)
#     owner = models.CharField(max_length=100)
#     location = models.CharField(max_length=200)
#     location_length = models.CharField(max_length=200, blank=True, default=0)
#     location_width = models.CharField(max_length=200, blank=True, default=0)
#     state = models.ForeignKey(State, on_delete=models.CASCADE)
#     theme = models.ForeignKey(Theme, on_delete=models.CASCADE)
#     capacity = models.IntegerField()
#     created_date= models.DateField(auto_now_add=True)
#     price = models.DecimalField(max_digits=8, decimal_places=2)
#     description = models.TextField(blank=True)
#     images = models.ImageField(upload_to="imagenes")
    
#     def __str__(self):
#       return self.name

# class OpeningHour(models.Model):
#     location = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='opening_hours')
#     day_of_week = models.IntegerField(choices=((1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')))
#     opening_time = models.TimeField()
#     closing_time = models.TimeField()
    
#     def __str__(self):
#       return self.location

chandelier_web/apps/home_page/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    date = models.DateTimeField(auto_now_add=True)
    affair = models.CharField(max_length=200)
    message = models.TextField(blank=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f"Message from {self.name} - {self.affair}"

# class Message(models.Model):
#     name = models.CharField(max_length=100)
#     email = models.EmailField()
#     date = models.DateField(auto_now_add=True)
#     affair = models.CharField(max_length=200)
#     message = models.TextField(blank=True)

#     def __str__(self):
#         return f"Mensaje of {self.name} - {self.affair}"

chandelier_web/apps/home_page/views.py
from django.shortcuts import render, redirect
from django.views import View
from chandelier_web.apps.admin_page_locations.models import Location, OpeningHour
from chandelier_web.apps.admin_page_states.models import State
from chandelier_web.apps.admin_page_themes.models import Theme
from chandelier_web.apps.home_page.models import Message
from chandelier_web.apps.home_page.form import MessageForm

# Create your views here.
class indexHome(View):
    def get(self, request, *args, **kwargs):
        locations = Location.objects.all()
        estados = State.objects.all()
        return render(request, 'index.html', {
            'locations': locations, 
            'estados': estados,
            })
    
class fastQuoteHome(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'fastQuote.html')
    
class quoteHome(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'quote.html')
    
class locationHome(View):
    def get(self, request ,reference, id):
        temas = Theme.objects.all()
        dato = None
        places = None
        if reference != "all":
            if reference == "estado":
                dato = State.objects.get(id=id)
                places = Location.objects.filter(state=id)
            else:
                dato = Theme.objects.get(id=id)
                places = Location.objects.filter(theme=id)
        else:
            places = Location.objects.all()
        new_reference = reference
        return render(request, 'location.html',{
            'temas':temas,
            'new_reference':new_reference,
            'dato':dato,
            'locations':places,
        })

class locationInfoHome(View):
    def get(self, request, id, **kwargs):
        location = Location.objects.get(id=id)
        opening_hours = OpeningHour.objects.filter(location=location)
        
        return render(request, 'locationInfo.html', {
            'location': location,
            'opening_hours': opening_hours,
        })
    
class aboutUsHome(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'aboutUs.html')
    
class contactHome(View):
    def get(self, request, *args, **kwargs):
        form = MessageForm()
        
        return render(request, 'contactUs.html', {
            'form': form,
        })
    
    def post(self, request, *args, **kwargs):
        form = MessageForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            return render(request, 'contactUs.html', {
                'form': form,
            })
        return redirect('contactHome')

chandelier_web/apps/home_page/templates/aboutUs.html
{% extends 'baseHome.html' %}

{% block title %}Acerca de nostros{% endblock %}

{% load static %}

{% block content %}
<!-- Hero -->
<section class="section-header bg-primary text-white pt-6 pb-4"></section>
<!-- End of Hero section -->

<!-- about section -->
<section class="section section-sm">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h2>Acerca de nosotros</h2>
                <p>Somos un equipo apasionado de profesionales dedicados a hacer realidad tus sueños. Con años de
                    experiencia en la industria de eventos, nos especializamos en ayudarte a planificar y organizar
                    eventos
                    inolvidables que superen tus expectativas.</p>
                <p>Ya sea que estés planeando una boda, una fiesta de cumpleaños o cualquier otro tipo de evento,
                    nuestro
                    objetivo es brindarte un servicio excepcional, atención personalizada y soluciones creativas que
                    hagan de
                    tu evento algo único y especial.</p>
            </div>
            <div class="col-lg-6">
                <img src="{% static 'img/office.png' %}" alt="Imagen de equipo" class="img-fluid">
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <h3>Misión</h3>
                <p>Proin volutpat eleifend orci, at congue enim accumsan vel. Sed non faucibus nunc. Maecenas sed sapien
                    aliquet, efficitur sapien non, ullamcorper ligula. Curabitur in ex quis dui lacinia lobortis. Nullam
                    volutpat lacus id diam convallis facilisis.</p>
            </div>
            <div class="col-md-6">
                <h3>Visión</h3>
                <p>Nullam sagittis metus sed justo lacinia auctor. Vivamus et purus volutpat, tempor elit id, pharetra
                    risus. Sed non felis pulvinar, tristique nisl eu, suscipit mi. Fusce iaculis nibh a leo egestas, vel
                    efficitur massa tincidunt.</p>
            </div>
        </div>
    </div>
</section>
<!-- end about section -->

<!-- personal section -->
<section class="section section-sm">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center mb-5">
                <h2>Nuestro equipo</h2>
            </div>
            <div class="col-12 col-md-6 col-lg-4 mb-5 mb-lg-0">
                <div class="card border-0 text-center">
                    <div class="card-header border-0 bg-white">
                        <img src="{% static 'img/team/profile-picture-2.jpg' %}" class="card-img-top rounded shadow border-0" alt="Christopher Avatar">
                    </div>
                    <div class="card-body">
                        <span class="card-subtitle text-gray fw-normal">Sales</span>
                        <h3 class="h4 card-title mt-2">Christopher Wood</h3>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4 mb-5 mb-lg-0">
                <div class="card border-0 text-center">
                    <div class="card-header border-0 bg-white">
                        <img src="{% static 'img/team/profile-picture-3.jpg' %}" class="card-img-top rounded shadow border-0" alt="Bonnie Avatar">
                    </div>
                    <div class="card-body">
                        <span class="card-subtitle text-gray fw-normal">Marketing</span>
                        <h3 class="h4 card-title mt-2">Bonnie Green</h3>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card border-0 text-center">
                    <div class="card-header border-0 bg-white">
                        <img src="{% static 'img/team/profile-picture-4.jpg' %}" class="card-img-top rounded shadow border-0" alt="Neil Avatar">
                    </div>
                    <div class="card-body">
                        <span class="card-subtitle text-gray fw-normal">Invoice</span>
                        <h3 class="h4 card-title mt-2">Neil Sims</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end personal sectio -->
{% endblock %}

chandelier_web/apps/home_page/templates/contactUs.html
{% extends 'baseHome.html' %}
{% load static %}{% load crispy_forms_tags %}

{% block title %}Contactanos{% endblock %}


{% block content %}
<!-- Hero -->
<section class="section section-header pb-11 bg-primary text-white">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-xl-8 text-center">
                <h1 class="display-2 mb-3">Ponte en contacto hoy!</h1>
                <p class="lead">
                    ¡Estamos aquí para ayudarte! Si tienes alguna pregunta, consulta o simplemente quieres obtener más
                    información sobre nuestros servicios, no dudes en contactarnos. Nuestro equipo de atención al
                    cliente estará encantado de atenderte y brindarte la asistencia que necesites.
                </p>
            </div>
        </div>
    </div>
</section>

<!-- Section -->
<div class="section py-0">
    <div class="container mt-n10">
        <div class="row">
            <div class="col-12">
                <iframe class="map rounded" id="gmap_canvas"
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d17468.80375957843!2d-92.9877774259477!3d17.96538689924487!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85edd6e2d6c16f97%3A0x82d93b6735175fb!2sClub%20Deportivo%20Tabasco!5e0!3m2!1ses!2smx!4v1685385405492!5m2!1ses!2smx"></iframe>
            </div>
        </div>
    </div>
</div>

<!-- Section -->
<section class="section section-lg pt-6">
    <div class="container">
        <div class="row justify-content-center mb-5 mb-lg-6">
            <div class="col-12 col-lg-8">
                <!-- Contact Card -->
                <div class="card shadow border-0 p-2 p-md-3 p-lg-5">
                    <div class="card-header bg-white border-0 text-center">
                        <h2>Quieres contactar con nosotros?</h2>
                        <p>Genial! cuentanos tus dudas</p>
                    </div>
                    <div class="card-body px-0 pt-0">
                        <form method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-primary">
                                Enviar
                            </button>
                        </form>
                    </div>
                </div>
                <!-- End of Contact Card -->
            </div>
        </div>
    </div>
</section>
<!-- End of section -->
{% endblock %}

chandelier_web/apps/home_page/templates/fastQuote.html
{% extends 'baseHome.html' %}

{% block title %}Cotizacion Rapida{% endblock %}

{% load static %}

{% block content %}
<!-- Hero -->
<section class="section-header bg-primary text-white pt-6 pb-4">
  <div class="container">
    <div class="row justify-content-center text-center">
      <div class="col-lg-8">
        <h1 class="display-3 fw-normal my-4">
          ¡Encuentra la inspiración que estás buscando, déjanos sorprenderte con opciones únicas y emocionantes para tu
          próximo gran evento!
        </h1>
      </div>
    </div>
  </div>
</section>
<!-- End of Hero section -->
<!-- Quote section -->
<section class="section section-sm bg-primary-app">
  <div class="container mt-5">
    <h1>Cotización Rapida</h1>
    <h5>Tiene en mente algo pero no sabe que hacer?, no se preocupe para eso estamos!</h5>
    <form>
      <div class="mb-3">
        <label for="nombre" class="form-label">Nombre</label>
        <input type="text" class="form-control" placeholder="James Smith" id="nombre" required>
      </div>
      <div class="mb-3">
        <label for="email" class="form-label">Correo electrónico</label>
        <input type="email" class="form-control" placeholder="example@company.com" id="email" required>
      </div>
      <div class="mb-3">
        <label for="telefono" class="form-label">Teléfono</label>
        <input type="tel" class="form-control" placeholder="123456789" id="telefono" required>
      </div>
      <div class="mb-3">
        <label for="tipo-evento" class="form-label">Tipo de Evento</label>
        <select class="form-select" id="tipo-evento" required>
          <option value="">Seleccionar</option>
          <option value="">Boda</option>
          <option value="">Cumpleaños</option>
          <option value="">Evento Corporativo</option>
          <option value="">Otro</option>
        </select>
      </div>
      <div class="mb-3">
        <label for="zona-evento" class="form-label">Estado del Evento</label>
        <select class="form-select" id="zona-evento" required>
          <option value="">Seleccionar</option>
          <option value="">CDMX</option>
          <option value="">Chiapas</option>
          <option value="">Tabasco</option>
          <option value="">Otro</option>
        </select>
      </div>
      <div class="mb-3">
        <label for="fecha-evento" class="form-label">Fecha del Evento</label>
        <input type="date" class="form-control" id="fecha-evento" required>
      </div>
      <div class="mb-3">
        <label for="mensaje" class="form-label">Mensaje</label>
        <textarea class="form-control" placeholder="Tell us more about your event" id="mensaje" rows="4"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Enviar Cotización</button>
    </form>
  </div>
</section>
<!-- end quote section -->
{% endblock %}

chandelier_web/apps/home_page/templates/location.html
{% extends 'baseHome.html' %}

{% block title %}Ubicaciones{% endblock %}

{% load static %}

{% block content %}
<!-- Hero -->
{% if new_reference != "all" %}
<section class="section-header bg-primary pt-6 pb-6 text-white">
    <div class="container p-3">
        <div class="row justify-content-between align-items-center">
            <div class="col-12 col-md-7 col-lg-6 text-center text-md-left">
                <!-- <div class="img-big-icon d-none d-lg-block image-container">
                    <img src="{{ dato.images.url}}" alt="" width="700" height="622" class="d-block my-1">
                </div> -->
                <h1 class="display-2 mb-2">{{ dato.name }}</h1>
                <p class="lead mb-2 text-muted">{{ dato.description }}</p>
            </div>
            <div class="col-12 col-md-5 d-none d-md-block text-center image-container">
                <img src="{{ dato.images.url}}" alt="">
            </div>
       </div>
        </div>
    </div>
</section>
{% else %}
<section class="section-header bg-primary pt-6 pb-4 text-white">
</section>
{% endif %}

<!-- End of Hero section -->
<!-- section of ubications -->
<section class="section section-sm">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 text-center">
                <h1 class="display-2 mb-3">Blank starter page</h1>
                <p>Hello world!</p>
            </div>
        </div>
        <div class="row">
            <div class="album">
                <div class="pt-4 pb-4">
                    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-3">
                        {% for location in locations %}
                        <div class="col">
                            <div class="card shadow-hover">
                                <img src="{{ location.images.url}}" class="card-img-top" alt="..." />
                                <div class="card-body">
                                    <h5 class="card-title">{{ location.name }}</h5>
                                    <p class="card-subtitle">{{ location.location }}</p>
                                    <div class="card-text">
                                        <strong>Tematica</strong> | 
                                        <small>{{ location.theme }}</small>
                                    </div>
                                    <p class="card-text">
                                        <strong>$</strong> <small>{{ location.price }}</small> | <span
                                            class="fas fa-user-circle"></span> <small>{{ location.capacity }}</small>
                                    </p>
                                    <a href="{% url 'locationInfoHome' location.id %}" class="btn btn-primary">Mas informacion</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item disabled">
                        <a class="page-link">Previo</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Siguiente</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</section>
<!-- end section of ubications -->
{% endblock %}

chandelier_web/apps/home_page/templates/locationInfo.html
{% extends 'baseHome.html' %}
{% load static %}{% load custom_tags %}

{% block title %}{{ location.name }}{% endblock %}

{% block content %}
<section class="section-header overflow-hidden pt-5 pb-5 bg-primary text-white"></section>

<section class="section section-sm">
    <div class="container">
        <div class="row mb-4">
            <div class="col-sm-12 col-md-8 col-lg-8 col-xl-8">
                <div class="card shadow">
                    <div class="card-body">
                        <div id="carouselExample" class="carousel slide">
                            <div class="carousel-inner">
                              <div class="carousel-item active">
                                <img src="{{ location.images.url }}" class="d-block w-100" alt="...">
                              </div>
                            </div>
                            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                              <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                              <span class="carousel-control-next-icon" aria-hidden="true"></span>
                              <span class="visually-hidden">Next</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">
                <div class="card shadow">
                    <div class="card-header py-3">
                        <h2>{{ location.name }}</h2>
                    </div>
                    <div class="card-body">
                        <p class="card-text">
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            &nbsp; <b>5.0</b>
                        </p>
                        <p class="card-text"><a href="#"><i class="fa-solid fa-location-dot"></i>&nbsp; {{ location.location }}</a></p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item ms-2"><i class="fa-solid fa-flag"></i>&nbsp; Estado: {{ location.state }}</li>
                        <li class="list-group-item ms-2"><i class="fa-solid fa-gift"></i>&nbsp; Tematica( <small class="cursor-pointer" data-bs-toggle="tooltip" data-bs-title="Esto no quiere decir que no se pueda usar para otro tipos de eventos sociales."><i>Opcional</i></small> ): {{ location.theme }}</li>
                    </ul>
                    <div class="card-footer">
                        <a href="" class="btn btn-secondary-app animate-down-1 shadow-hover">Cotizar ahora!</a>
                        <a href="" class="btn btn-outline-secondary-app animate-down-1 shadow-hover">
                            <i class="fa-solid fa-phone"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mb-4">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header py-3">
                        <h4>Detalles importantes</h4>
                    </div>
                    <div class="card-body">
                        <div class="row align-items-center text-center">
                            <div class="col p-4"><i class="fa-solid fa-users-rectangle fa-xl"></i>&nbsp; <span data-bs-toggle="tooltip" data-bs-title="Puede variar dependiendo del tamaño o del distribuidor, este es un numero aproximado.">Hasta {{ location.capacity }} personas</span></div>
                            <div class="col p-4"><i class="fa-solid fa-money-bill fa-xl"></i>&nbsp; <span data-bs-toggle="tooltip" data-bs-title="Coste de renta de la ubicacion, los servicios y demas pueden aumentar el precio.">Desde ${{ location.price }}</span></div>
                            <div class="col p-4"><i class="fa-solid fa-gift fa-xl"></i>&nbsp; <span data-bs-toggle="tooltip" data-bs-title="Esto no quiere decir que no se pueda usar para otro tipos de eventos sociales.">Para eventos tipo  "{{ location.theme }}"</span></div>
                        </div>
                        <div class="row align-items-center text-center">
                            <div class="col p-4"><i class="fa-solid fa-square-parking fa-xl"></i>&nbsp; <span data-bs-toggle="tooltip" data-bs-title="Consulte con el distribuidor la disponivilidad del mismo.">Con estacionamiento</span></div>
                            <div class="col p-4"><i class="fa-solid fa-user fa-xl"></i>&nbsp; <span>Dueño {{ location.owner }}</span></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mb-4">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header py-3">
                        <h4>Informacion</h4>
                    </div>
                    <div class="card-body">
                        <div class="d-flex flex-row mb-3">
                            <div class="pe-4"><small>En Chandelier desde: {{ location.created_date }}</small></div>
                            <div class="pe-4"><small>Ultima actualizacion: {{ location.created_date }}</small></div>
                        </div>
                        <h6 class="card-title">Descripcion</h6>
                        <p class="card-text">
                            {{ location.description }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mb-4">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header py-3">
                        <h4>Horarios Laborales</h4>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Dia</th>
                                    <th>Apertura</th>
                                    <th>Cierre</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for hour in opening_hours %}
                                    <tr>
                                        <td>{{ hour.get_day_of_week_display }}</td>
                                        <td>{{ hour.opening_time }}</td>
                                        <td>{{ hour.closing_time }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow">
                    <div class="card-header py-3">
                        <h4>Detalles Tecnicos</h4>
                    </div>
                    <div class="card-body">
                        El terreno tiene una superficie de <strong>{{location.location_length|floatformat:2|multiply:location.location_width|floatformat:2}}m²</strong>, 
                        con unas dimensiones de <strong>{{location.location_length|floatformat:2}}m de largo</strong> por <strong>{{ location.location_width|floatformat:2 }}m de ancho.</strong>
                        {% if location.location_length != location.location_width %}
                        <img src="{% static 'img/terrain/rectangulo.png' %}" class="mx-auto d-block" alt="Terreno rectangular"/>
                        {% else %}
                        <img src="{% static 'img/terrain/cuadrado.png' %}" class="mx-auto d-block" alt="Terreno cuadrado"/>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}